### ISSUE TITLE
Issue with URI encoded in lowercase by mod_auth_cas

### ISSUE THREAD

**Issue by dbz78** [apereo/mod_auth_cas#108] opened 2016-08-26 17:23 UTC
Hello,
With colleagues in my company, we are currently trying to fix issues with an application relying on mod_auth_cas for authentication. Some problems are related to certificates. Some others are related to the **format of URI in a complex connection chain**.

Let's have a look to an architecture schema:

```
internal user <-> browser <-----------+-----------------+
                                      |                 |
                              internal frontend <-> internal cas
                                      ^         *       ^
                                      |                 |
                                      v                 v
                              internal database   internal directory
                                      ^                 ^
                                      |                 |
~~~~~~~~~~~ LAN / DMZ BOUNDARY ~~~~~~~|~~~~~~~~~~~~~~~~~|~~~~~~~~~~~
                                      v                 v
                              external frontend <-> external CAS
                                      ^               ^  ^    /\$$
====== DMZ / INTERNET BOUNDARY =======|===============|==|====||===
                                      v               |  |    ||
external user <-> browser <-----------+---------------+  |    ||
                                      |                  |    ||
partner user <-> browser <------------+------------------+    ||
                                                              ||
====== DMZ / INTERNET BOUNDARY ===============================||===
                                                              \/
                                                     partner CAS
                                                          ^
                                                          |
                                                          v
                                                     whatever ???
```

Our certificate issues occur on the connection side indicated by the *, and are not the subject here.

Our other problem with URI occurs on the connection side indicated by the **$$**. Here are some explanations:

Some users from a partner are supposed to use our application. When such an user requests a first page on external frontend, external CAS login page displays, and offer her/him an alternate authentication scheme. If she/he selects this scheme, her/his browser is redirected to the partner's CAS login page. Once she/he authenticates there, tickets are sent back, our external CAS validates with partner's CAS, then generates its own tickets, then allows access to partner user.

Our problem is: When validating partner's tickets, our CAS fails because the original service's URI has been encoded in **lowercase** by mod_auth_cas!

The partner user requests the following URI:

> http://frontend.myorg.tld/MYAPP/index.do

The mod_auth_cas module in the Apache frontend instantly redirects the browser to:

> https://cas.myorg.tld/cas/login?service=http%3a%2f%2ffrontend.myorg.tld%2fMYAPP%2findex.do

Note that the URI has been encoded by mod_auth_cas in **lowercase**: %3a, %2f

In the external CAS login page, the partner user clicks a button to redirect to partner's CAS. In the browser, the URI appears to be:

> https://cas.partner.tld/cas/login?service=https://cas.myorg.tld/cas/login?service=http%3a%2f%2ffrontend.myorg.tld%2fMYAPP%2findex.do

After the user has succesfully authentified, the browser is redirected back to the external CAS login page, wich displays a failure message, though the URI is:

> https://cas.myorg.tld/cas/login?service=http%3a%2%2ffrontend.myorg.tld%2fMYAPP%2findex.do&ticket=ST-xxxx

Unfortunately, the partner's technical team was in a "_our platform is perfect. problem comes from your platform. we won't spend neither lab platform nor time to help_" state of mind. However, looking at some logs, they eventually told us that if the URI were encoded in uppercase they would work (how they found out, we don't know). With some hand-editing in a browser, we could verify that it was true!

There were some more argument about _"your platform doesn't conform to internet RFCs_", but we checked that lowercase is **valid**, though not **adviced**:

> https://tools.ietf.org/html/rfc3986#section-2.1
> `The uppercase hexadecimal digits 'A' through 'F' are equivalent to the lowercase digits 'a' through 'f', respectively.  If two URIs differ only in the case of hexadecimal digits used in percent-encoded octets, they are equivalent.  For consistency, URI producers and normalizers **should use uppercase hexadecimal digits** for all percent-encodings.
> `

As the mod_auth_cas module is embedded in a global software solution provided by an ISV, we couldn't modify it from a custom fork of mod_auth_cas source code (both for contracting and technical issues).

However we had to do something, so eventually we solved that by **hex-editing the mod_auth_cas.so** Windows DLL (yes, for some reason, frontend Apache runs on a Windows platform).
This **_dirty_** fix works like a charm, and is today in production.
But this is _**not satisfactory**_, as everything could go kaboom the next time the ISV provides a patch or an update.

In order to get a more professional and stable solution, here are some questions and proposals:
1. Did anyone ever encounter such a situation? Any idea of root cause (we spent some time looking at settings and logs from firewalls, proxies ...)? Any idea of some seemingly harmless default setting to change on either mod_auth_cas, Apache, cas server, whatever ... to fix this?
2. We could ask ISV to build the mod_auth_cas.so from a custom fork of public source code. But it would be easier to have them agree if a solution is provided in the public, official trunk here in github. Moreover, this would benefit to everyone in the community. We understand that RFC3986 is clear that lowercase percent encoding **is valid**, so the mod_auth_cas community has no reason to take care, but this is true life in the true world of interconnected, distributed information systems: Offering a possible solution for that problem when it occurs is a _**nice-to-have**_ (if there is no other simpler solution through setting, of course).

Here is some results of our investigations: Responsible code is _**getCASService()**_ function from line 540 to line 583 in **mod_auth_cas.c**:

```
/*
 * Responsible for creating the 'service=' parameter.  Constructs this
 * based on the contents of the request_rec because r->parsed_uri lacks
 * information like hostname, scheme, and port.
 */
char *getCASService(const request_rec *r, const cas_cfg *c)
{
    const apr_port_t port = r->connection->local_addr->port;
    const apr_byte_t ssl = isSSL(r);
    const apr_uri_t *root_proxy = &c->CASRootProxiedAs;
    char *scheme, *port_str = "", *service;
    apr_byte_t print_port = TRUE;

#ifdef APACHE2_0
    scheme = (char *) ap_http_method(r);
#else
    scheme = (char *) ap_http_scheme(r);
#endif

    if (root_proxy->is_initialized) {
        service = apr_psprintf(r->pool, "%s%s%s%s",
            escapeString(r, apr_uri_unparse(r->pool, root_proxy, 0)),
            escapeString(r, r->uri),
            (r->args != NULL ? "%3f" : ""),
            escapeString(r, r->args));
    } else {
        if (ssl && port == 443)
            print_port = FALSE;
        else if (!ssl && port == 80)
            print_port = FALSE;

        if (print_port)
            port_str = apr_psprintf(r->pool, "%%3a%u", port);

        service = apr_pstrcat(r->pool, scheme, "%3a%2f%2f",
            r->server->server_hostname,
            port_str, escapeString(r, r->uri),
            (r->args != NULL && *r->args != '\0' ? "%3f" : ""),
            escapeString(r, r->args), NULL);
    }
    if (c->CASDebug)
        ap_log_rerror(APLOG_MARK, APLOG_DEBUG, 0, r, "CAS Service '%s'", service);
    return service;
}
```

Instead of using in-line hard-coded string constants (the "_culprits_" here: "%%3a%u", "%3a%2f%2f", "%3f" twice), there could be some #DEFINEs:

```
#DEFINE CAS_FORMAT_PORT_LOWER "%%3a%u"
#DEFINE CAS_FORMAT_PORT_UPPER "%%3A%U"
#DEFINE CAS_FORMAT_SEP_LOWER "%3a%2f%2f"
#DEFINE CAS_FORMAT_SEP_UPPER "%3A%2F%2F"
#DEFINE CAS_FORMAT_QUESTION_LOWER "%3f"
#DEFINE CAS_FORMAT_QUESTION_UPPER "%3F"
```

The same is true for _**urlEncode()**_ from line 836 to line 882:

```
char *urlEncode(const request_rec *r, const char *str,
                                const char *charsToEncode)
{
    char *rv, *p;
    const char *q;
    size_t i, j, size, limit, newsz;
    char escaped = FALSE;

    if(str == NULL)
        return "";

    size = newsz = strlen(str);
    limit = strlen(charsToEncode);

    for(i = 0; i < size; i++) {
        for(j = 0; j < limit; j++) {
            if(str[i] == charsToEncode[j]) {
                /* allocate 2 extra bytes for the escape sequence (' ' -> '%20') */
                newsz += 2;
                break;
            }
        }
    }
    /* allocate new memory to return the encoded URL */
    p = rv = apr_pcalloc(r->pool, newsz + 1); /* +1 for terminating NULL */
    q = str;

    do {
        escaped = FALSE;
        for(i = 0; i < limit; i++) {
            if(*q == charsToEncode[i]) {
                sprintf(p, "%%%x", charsToEncode[i]);
                p+= 3;
                escaped = TRUE;
                break;
            }
        }
        if(escaped == FALSE) {
            *p++ = *q;
        }

        q++;
    } while (*q != '\0');
    *p = '\0';

    return(rv);
}
```

Here the string constant to convert to a #DEFINE is "%%%x". There could be:

```
#DEFINE CAS_FORMAT_URLENCODE_LOWER "%%%x"
#DEFINE CAS_FORMAT_URLENCODE_UPPER "%%%X"
```

_**AND**_ this could be switched back and forth in **adding a new configuration directive** that could be:

```
Directive:       CASUriEncoding
Default:         lower
Possible values: lower|upper
```

If you arrived here, thanks for reading ;-).
Any answer, advice, clue, comments ... are welcome!

**Comment by dhawes** [comment] 2016-08-27 01:44
> Unfortunately, the partner's technical team was in a "our platform is perfect. problem comes from your platform. we won't spend neither lab platform nor time to help" state of mind. However, looking at some logs, they eventually told us that if the URI were encoded in uppercase they would work (how they found out, we don't know). With some hand-editing in a browser, we could verify that it was true!

What CAS server software are you running? I've never heard or seen of this issue with CAS server software. In my mind the server is the most obvious place to fix this issue, since as you noted both upper and lower case hex chars are valid. If this is a supported CAS server, file an issue and get it fixed!

> As the mod_auth_cas module is embedded in a global software solution provided by an ISV, we couldn't modify it from a custom fork of mod_auth_cas source code (both for contracting and technical issues).
>
> However we had to do something, so eventually we solved that by hex-editing the mod_auth_cas.so Windows DLL

So you couldn't modify it, so you modified it? Just kidding, I appreciate the hack. ;)

> Did anyone ever encounter such a situation? Any idea of root cause (we spent some time looking at settings and logs from firewalls, proxies ...)? Any idea of some seemingly harmless default setting to change on either mod_auth_cas, Apache, cas server, whatever ... to fix this?

I haven't been able to find much with some quick googling, but maybe someone will chime in if they have. I think you covered the root cause well: whatever CAS server is being used has issues with lower case hex characters. I would look at that server and go from there.

> ... adding a new configuration directive ...

I appreciate the analysis, but I think adding more directives is overkill in this case. I'd be more amenable to just making everything uppercase by default. It's a simple fix and should not affect any CAS server that I'm aware of. I'll let anyone else weigh in here and then whip up a merge request if there are no objections.

I'm still curious about this oddball CAS server...

**Comment by pames** [comment] 2016-08-27 04:02
So, feel free to ignore this comment, but: I agree wholeheartedly about the fact that, absent the spec mentioning anything specific about upper/lowercase etc. about how parameters should be encoded (as opposed to directly reflecting it modulo the encoding requirements of the transport channel), the server should be fixed.

Yes, it's a simple fix and shouldn't affect any servers, but this server seems to behave differently than any (all?) other reasonable server implementations and catering to it just makes things harder for the overall CAS server and client ecosystem, so I would not advocate enabling it - an org that depends on this "broken" CAS server can maintain an internal fork and/or apply pressure via their support channels to improve compatibility for every customer.

**Comment by dbz78** [comment] 2016-08-29 07:52
Hello dhawes, hello pames,

About adding a new directive being overkill, I disagree: as dhawes says, mod_auth_cas has been working perfectly for years with lowercase. Switching **_once and for all_** in uppercase would jeopardize thousands of working platforms. Having the **capability** to switch **_when needed only_** should be better.

But I agree that the true solution is finding what component in the connection chain is faulty. Fixing the root cause (some setting somewhere - just have to find where :-( ) is the proper, professional approach.

As I said in another post, we have had a review, and decided to dig thoroughly into our CAS servers' configuration files, since they are in a farm behind a proxy. But problem could come from the CAS server of the partner, and it will be difficult to prove it and enforce said "_partner_" to do something.

More on this later on,

**Comment by dhawes** [comment] 2016-08-29 21:50
> Having the capability to switch when needed only should be better.

I would argue that adding the capability is overkill provided there is only one server that has been reported to have the issue (and that server software is unknown, so we can't even verify this issue).

After thinking about it more, I agree with @pames that a change does not seem justified.

**Comment by dbz78** [comment] 2016-09-01 10:27
Hello dhawes, hello pames,

Though it doesn't help us, I eventually agree that WE have to find the root cause ans solve it.

When we manage, I will make the community know about it.

**Closed** 2020-02-05 22:17 UTC
