### ISSUE TITLE
RequestID is missing in SAML

### ISSUE THREAD

**Issue by fbacchella** [apereo/mod_auth_cas#148] opened 2018-07-17 12:39 UTC
At https://github.com/apereo/cas/blob/master/support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/authentication/principal/SamlServiceFactory.java#L107

The attribute RequestID can't be null.
Looking at the saml example from documentation from https://apereo.github.io/cas/5.3.x/protocol/SAML-Protocol.html#sample-request

    <SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
      <SOAP-ENV:Header/>
      <SOAP-ENV:Body>
        <samlp:Request xmlns:samlp="urn:oasis:names:tc:SAML:1.0:protocol" MajorVersion="1"
          MinorVersion="1" RequestID="_192.168.16.51.1024506224022"
          IssueInstant="2002-06-19T17:03:44.022Z">
          <samlp:AssertionArtifact>
            ST-1-u4hrm3td92cLxpCvrjylcas.example.com
          </samlp:AssertionArtifact>
        </samlp:Request>
      </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>

But with mod_auth_cas-1.1, the request is:

```
<?xml version="1.0" encoding="utf-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <samlp:Request xmlns:samlp="urn:oasis:names:tc:SAML:1.0:protocol"  MajorVersion="1" MinorVersion="1">
            <samlp:AssertionArtifact>ST-1-XXXXX</samlp:AssertionArtifact>
        </samlp:Request>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

The RequestID is missing. And indeed, at https://github.com/apereo/mod_auth_cas/blob/master/src/mod_auth_cas.c#L1827:

		samlPayload = apr_psprintf(r->pool, "<?xml version=\"1.0\" encoding=\"utf-8\"?><SOAP-ENV:Envelope xmlns:SOAP-ENV=\"http://schemas.xmlsoap.org/soap/envelope/\"><SOAP-ENV:Header/><SOAP-ENV:Body><samlp:Request xmlns:samlp=\"urn:oasis:names:tc:SAML:1.0:protocol\"  MajorVersion=\"1\" MinorVersion=\"1\"><samlp:AssertionArtifact>%s%s</samlp:AssertionArtifact></samlp:Request></SOAP-ENV:Body></SOAP-ENV:Envelope>",ticket, getCASRenew(r));

No RequestID. So SAMLv1 is not usable with mod_auth_cas and CAS 5. What can I doing ?

**Comment by dhawes** [comment] 2018-07-17 17:40
The schema does seem to require the RequestID:

https://www.oasis-open.org/committees/download.php/3407/oasis-sstc-saml-schema-protocol-1.1.xsd

That said, have you tested CAS 5? This clearly has worked for other CAS versions.

**Comment by fbacchella** [comment] 2018-07-17 19:36
I'm testing it with CAS 5.3.1. It was worked on 3, and now it's broken. I will not be able to migrate until it's fixed.

**Comment by fbacchella** [comment] 2018-07-18 08:01
What is missing in the example I gave you ? The first xml document I gave you is extracted from CAS documentation, it works. The second is the result of a tcpdump using the current version of mod_auth_cas.

There is a link to the current version of CAS code where you see:

        val requestIdAttribute = requestChild.getAttribute("RequestID");
        return requestIdAttribute.getValue();

What else than an NPE do you expect from such code ?

**Comment by dhawes** [comment] 2018-07-18 16:55
Sure, I'd expect a NPE from that code, but a log message or stack trace may be useful in other ways.

It looks like the CAS behavior was changed in commit e40de650f7a82149f80c9700299d629ccb6c9fc7. Before that, it looks like a null RequestID could be handled.

I'll need to track down some kind of documentation or review the Java cas client to determine the correct value for RequestID so we can fix this issue.

**Comment by dhawes** [comment] 2018-07-18 17:14
Java CAS client RequestID:

https://github.com/apereo/java-cas-client/blob/2af0d7d13c5b405fee0d0e8f170d5ffe0b844dea/cas-client-support-saml/src/main/java/org/jasig/cas/client/validation/Saml11TicketValidator.java#L224

**Comment by serac** [comment] 2018-07-18 21:07
@dhawes _RequestID_ just needs to be unique on a per-request basis. OWASP [1] recommends 16 bytes of entropy in session identifiers, which have similar requirements; the CAS client is consistent with that recommendation.

[1] https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Session_ID_Length

**Comment by davidgelhar** [comment] 2019-02-26 16:07
@dhawes Can your fix be merged into master?

**Comment by dhawes** [comment] 2019-03-01 22:00
This was a quick patch with little testing on my part. I'm not ready to merge it until it's reviewed and tested.

Have you verified the fix works in your environment?

**Comment by davidgelhar** [comment] 2019-03-07 01:04
No, we haven’t verified the fix. 

It turns out that the latest version of CAS 6.x server is tolerant of the missing requestID, so the issue is no longer urgent for us. Seems like it would be good to get the fix in at some point just to align with the SAML spec, but if it’s working with current servers it’s not nearly so critical 

Thanks 

David

**Comment by fbacchella** [comment] 2019-08-14 08:10
Any hope for a 1.3 with this patch merged ? Since switching to CAS 5.3.11, I'm getting a lot of:

    SAML request body does not specify the RequestID attribute. This is a required attribute per the schema definition and MUST be provided by the client.  RequestID needs to be unique on a per-request basis and per OWASP, it may be 16 bytes of entropy in session identifiers which have similar requirements. While CAS does allow the RequestID attribute to be optional for the time being to preserve backward compatibility, this behavior MUST be fixed by the client and future CAS versions begin to enforce the presence of RequestID more forcefully to remain compliant with schema and protocol.

in the logs

**Comment by dhawes** [comment] 2019-08-16 21:02
Are you able to patch and verify that it works correctly in your environment? That feedback will go a long way towards merging it.

**Comment by ruckc** [comment] 2019-08-19 23:49
I've been using @dhawes 's fix in prod for 7 months or, seems solid.

**Closed** 2019-10-04 16:19 UTC
